export function ProblemSection() {
  // Shared text styles for cards
  const cardBodyStyle = {
    fontFamily: 'var(--font-nav)',
    fontSize: '14px',
    lineHeight: '1.6',
    color: 'var(--textSecondary)',
  }

  return (
    <section id="problem" className="py-24" style={{ backgroundColor: 'var(--bg0)' }}>
      <div className="mx-auto max-w-7xl px-6">
        <div className="grid gap-16 lg:grid-cols-2">
          {/* Left: The Problem */}
          <div className="space-y-6">
            {/* Label with dot */}
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full" style={{ backgroundColor: 'var(--critical)' }} />
              <span 
                className="text-xs font-medium uppercase tracking-wider"
                style={{ fontFamily: 'var(--font-nav)', color: 'var(--textTertiary)' }}
              >
                The Problem
              </span>
            </div>
            
            <h2 
              className="text-3xl font-bold tracking-tight"
              style={{ fontFamily: 'var(--font-nav)', color: 'var(--textPrimary)' }}
            >
              Real-World Operations Are Messy
            </h2>
            
            <p style={{ fontFamily: 'var(--font-nav)', color: 'var(--textSecondary)', lineHeight: '1.7' }}>
              When telemetry is incomplete, contradictory, or degraded, operators still 
              have to make calls. The problem isn't the alarms—it's that there's no 
              defensible record of what was known, what was uncertain, and why a 
              decision was reasonable at the time.
            </p>

            {/* 2x2 Metric Grid */}
            <div className="grid grid-cols-2 gap-4 pt-4">
              {[
                { metric: '68%', label: 'of incidents involve sensor conflict' },
                { metric: '4.2min', label: 'avg decision window under duress' },
                { metric: '91%', label: 'of audits cite "missing context"' },
                { metric: '0', label: 'receipts generated by legacy tools' },
              ].map((item) => (
                <div 
                  key={item.label}
                  className="rounded-[8px] p-4"
                  style={{ 
                    backgroundColor: 'var(--surface0)', 
                    border: '1px solid var(--border0)',
                  }}
                >
                  <div 
                    className="text-2xl font-bold"
                    style={{ fontFamily: 'var(--font-nav)', color: 'var(--textPrimary)' }}
                  >
                    {item.metric}
                  </div>
                  <div style={cardBodyStyle}>{item.label}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Right: The Solution */}
          <div className="space-y-6">
            {/* Label with dot */}
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full" style={{ backgroundColor: 'var(--trust)' }} />
              <span 
                className="text-xs font-medium uppercase tracking-wider"
                style={{ fontFamily: 'var(--font-nav)', color: 'var(--textTertiary)' }}
              >
                The Solution
              </span>
            </div>
            
            <h2 
              className="text-3xl font-bold tracking-tight"
              style={{ fontFamily: 'var(--font-nav)', color: 'var(--textPrimary)' }}
            >
              Decision Infrastructure That Defends Itself
            </h2>
            
            <p style={{ fontFamily: 'var(--font-nav)', color: 'var(--textSecondary)', lineHeight: '1.7' }}>
              LOGOSYN wraps every operator action with evidence lineage, trust scoring, 
              and machine-readable reason codes—so that months later, an auditor or 
              review board can see exactly why the call was reasonable given what 
              was known.
            </p>

            {/* 2x2 Feature Grid */}
            <div className="grid grid-cols-2 gap-4 pt-4">
              {[
                { title: 'Evidence Lineage', desc: 'Every input traced to source' },
                { title: 'Trust Scoring', desc: 'Quantified confidence, not guesswork' },
                { title: 'Contradiction Flags', desc: 'Conflicts surfaced, not hidden' },
                { title: 'Audit Receipts', desc: 'Immutable record at time of action' },
              ].map((item) => (
                <div 
                  key={item.title}
                  className="rounded-[8px] p-4"
                  style={{ 
                    backgroundColor: 'var(--surface0)', 
                    border: '1px solid var(--border0)',
                  }}
                >
                  <div 
                    className="font-semibold mb-1"
                    style={{ fontFamily: 'var(--font-nav)', color: 'var(--textPrimary)' }}
                  >
                    {item.title}
                  </div>
                  <div style={cardBodyStyle}>{item.desc}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
